### ISSUE TITLE
右下角页数无法正常获取

### ISSUE THREAD

**Issue by 1052726643** [Byaidu/copymanga-helper#1]
首先非常感谢此脚本！

双页模式下，由于页数不能正常读取，导致插入单页功能，和上下整页翻页功能（包括↑↓快捷键和鼠标点击区域）不能正常使用。

如以下网址：
https://copymanga.com/comic/yuzhezhiye/chapter/790ac472-67a0-11eb-b5a6-00163e0ca5bd
https://copymanga.com/comic/yishijieshushu/chapter/0b885eee-9137-11eb-a0bb-024352452ce0

另外还有一个小建议：左侧sidebar边栏的触发范围可以再缩小一点，比如width:10vw，现在的宽度过宽，鼠标滑过漫画左侧内容很容易滑出目录。

**Comment by Byaidu** [comment]
问题已修复，感谢反馈
