### ISSUE TITLE
[Bug] iOS 端下一章点击无响应。

### ISSUE THREAD

**Issue by ShiinaKaze** [Byaidu/copymanga-helper#13]
![image](https://user-images.githubusercontent.com/89641145/228296893-1b13cb49-2edc-4d97-9bda-2737287d100a.png)

iOS的布局是这种情况。

**Comment by Byaidu** [comment]
可能是插件问题，我这里用stay2是正常的

**Comment by ShiinaKaze** [comment]
> 可能是插件问题，我这里用stay2是正常的

用的userscript，GitHub开源的，我试试stay。
