### ISSUE TITLE
脚本寄了？greasyfork上也被移除了

### ISSUE THREAD

**Issue by Yjun233** [Byaidu/copymanga-helper#14]
发生什么事了（

**Comment by Byaidu** [comment]
官方投诉，所以下架了，可能之后会恢复吧

好心人也可以上去开个镜像

**Comment by Byaidu** [comment]
看不了的原因是官方给图片请求套了个AES，虽然这个随手就能解

但是如果把解密脚本公开出来，官方肯定又会投诉，到时候大家都看不了

**Comment by Aak-lungmen** [comment]
大悲 蹲镜像+解密 没有增强组件的我无比弱小

**Comment by Stabrinai** [comment]
官方还加了个请求限制，请求太快的话就提示210了

**Comment by Stabrinai** [comment]
暂时应该是可以用了，下载的话，每一话下载完成之后延迟一秒再请求下一话。

**Comment by Yjun233** [comment]
感谢大佬。另外我发现修改网页标题的那行代码是不是被误删了？

**Comment by Stabrinai** [comment]
应该是……我等会再改改

**Comment by AptxAngel** [comment]
用不了了捏，，

**Comment by Stabrinai** [comment]
> 用不了了捏，，

版本号

**Comment by dyxang** [comment]
> > 用不了了捏，，
> 
> 版本号

10.6

**Comment by Stabrinai** [comment]
> > > 用不了了捏，，
> > 
> > 
> > 版本号
> 
> 10.6

更新到最新版本再试 最新是10.8
