### ISSUE TITLE
今天加载脚本无法显示漫画了

### ISSUE THREAD

**Issue by blacklein** [Byaidu/copymanga-helper#3]
今天加载脚本，点击集数后，阅读页面无法显示漫画了，但取消脚本后可以正常显示漫画，不知道什么原因

**Comment by Byaidu** [comment]
api被ban了，现在tachiyomi也不能访问

https://github.com/tachiyomiorg/tachiyomi-extensions/pull/12376

**Comment by blacklein** [comment]
那以后都不能用了还是等恢复呀？

**Comment by Byaidu** [comment]
今天似乎又恢复了，安装插件改一下浏览器 UA 就行

https://chrome.google.com/webstore/detail/user-agent-switcher-and-m/bhchdcejhohfmigjafbampogmaanbfkg

**Comment by blacklein** [comment]
试了下确实又可以用了，感谢告知
